### PR TITLE
change to support sentence weight in labelDoc case

### PR DESCRIPTION
**Pull request by ledw**
as discussed in https://github.com/facebookresearch/StarSpace/issues/99, adding sentence weight in labelDoc case.

### CODE REVIEW

**Comment by pommedeterresautee** [comment]
In this line
https://github.com/facebookresearch/StarSpace/pull/116/files#diff-cc3f76f032fe2ae8f52c99516b2d1dc7R62

There are 2 weights, one is the weight of the example, what is the other?

**Comment by pommedeterresautee** [comment]
I think I do.
For instance, in my very first use case where I try to perform query recomandation, let s say I have a session with 3 reformulations. I use trainmode 3 to get a similar representation of the 3 representations of the 3 reformulations, and the weight is number of opened documents, I should write:
```
weight:6 w1_reformulation1 w2_reformulation1 w3_reformulation1 w4_reformulation1 \t weight:29 w1_reformulation2 w2_reformulation2 w3_reformulation2 \t weight:2 w1_reformulation3 w2_reformulation3
```
Is that right?

**Comment by ledw** [comment]
@pommedeterresautee your first choice and second choice would work the same here. After this change the global weight is not supported in labelDoc case. Being able to specify sentence weight at the beginning of each sentence simply the example format. On the other hand, word weighted is needed in other cases (for instance, combine with image features), so it's also supported.

**Comment by jaseweston** [comment]
looks good to me, is there some added doc in the README?
have you checked it doesn't break anything in existing examples?

**Comment by ledw** [comment]
@jaseweston checked that it does not break existing examples. I'll update README on a follow up change.

**Pull request merged**
